### PR TITLE
Fixed issues that were stopping the json tmLanguage working

### PR DESCRIPTION
**Pull request by msarson**
Hi Brahn, 

I decided to take my first baby steps with trying to get VS Code working better with the syntax's.

A couple of things I found out, it is best in VS Code to use the JSON version of the tmLanguage files as apparently they don't need to be complied.

Also it seem to require the language file to be names language.tmLangauge.json, so have done that, and used a json tidy tool to format the file.

I'll play more over the weeks.

I think this helps with some code colouring as well. 

Cheers

### CODE REVIEW

**Comment by MarkGoldberg** [comment]
Excellent Mark, 
But please be careful here.
If I'm not mistaken this repo is live for the SublimeText Clarion package

**Comment by msarson** [comment]
@MarkGoldberg 
This is a valid point, I am not sure what is used in Sublime vs VS code. Does Sublime use the package.json file? as I had to change that.

I think Sublime is using the Clarion.tmLanguage file though, and I have not touched that.

I did remove some invalid comments that were in clarion.configuration.json.

The following is an image before my changes

image

and this is the result of the changes
image

You will note that syntax colouring seems to be working much better.

**Comment by MarkGoldberg** [comment]
You asked. 

> Does Sublime use the package.json file?

In short, I don't know
That said, I looked inside of a different ST3 package (Alignment)
and it does NOT have a package.json
however there is a package-metadata.json

**Comment by fushnisoft** [comment]
I think the `Clarion.JSON-tmLanguage` is used as part of the SublimeText build process, or at least ST2.
Which brings up a point, is anyone still wanting to retain ST2 support?

**Comment by msarson** [comment]
@fushnisoft The strange thing is if you change the name to Clarion.JSON-tmlanguage and alter the packages.json file accordingly then all the colouring problems come back. 

I will do some more testing around this, but I am wondering if at some point we are going to have to split the development of the two packages into different repos. Guessing this will cause some heart ache for the VS Code ppl, but might be a better option in the long term?

**Comment by fushnisoft** [comment]
>the strange thing is if you change the name to Clarion.JSON-tmlanguage and alter the packages.json

Oh, I didn't realise that was a name change. So you can have both.
The `Clarion.JSON-tmLanguage` was used as part of the process to build a syntax for Sublime Text 2 ( [ref](http://docs.sublimetext.info/en/latest/extensibility/syntaxdefs.html#creating-a-new-syntax-definition) ) 
Perhaps leave that as it was, leave `Clarion.tmLanguage` also and copy `Clarion.JSON-tmLanguage` to `Clarion.tmLanguage.json` for VSCode?

I notice that the VSCode help mentions both 

>VS Code recognizes two formats for grammar files, Plist (.tmLanguage) and JSON (.tmLanguage.json). Plist files are really verbose, so people usually compile them from other languages like YAML.
  -- https://code.visualstudio.com/docs/extensionAPI/language-support#_syntax-highlighting

It would be simplified if we can drop support for ST2 but it's also not too hard to retain I think. See if the above helps at all and I will run the PR through all version tomorrow to check that upgrading works smoothly too.

**Comment by fushnisoft** [comment]
@msarson 
I had a closer look and it seems to me that the only necessary changes to better support vscode are:
1. `"path": "./syntaxes/Clarion.tmLanguage.json"`
2. creating a copy of `Clarion.JSON-tmLanguage` called `Clarion.tmLanguage.json`

The only other changes that I support is adding `"Programming Languages"` to the categories.

There is no need to increment the version number, that happens when the [package is published](https://code.visualstudio.com/docs/extensions/publish-extension#_autoincrementing-the-extension-version) so I will include it in the commit after publishing (extra incrementing doesn't hurt, I only mention it here as an FYI!) 

Changing the case of `Clarion` seems unnecessary unless you can give me a good reason. They are already consistent as lowercase and I am pretty sure that changing them now breaks the upgrade path for already install extensions/packages (or possible the VSCode publish process) so I would be much more comfortable in leaving them as-is.

It's better to leave the `Clarion.JSON-tmLanguage` in the repo, it doesn't hurt VSCode and it helps SublimeText backward compatibility IMO.

**Comment by msarson** [comment]
Hi @fushnisoft 

**Casing: - package.json**
I have found it very important that the case of the "ID": attribute in the contributes, languages section in the file matches the "language": case in grammars and snippits. If they don't match, then the language doesn't show up in vs code.

**Clarion.tmlanguage.json**
I have installed an extension in VS Code. [TextMate Languages](https://github.com/Togusa09/vscode-tmlanguage/) 

This has a feature that will take a .tmLanguage file and convert to .tmLanguage.json. Meaning we can convert the .tmLanguage file any time a change has been made, I would guess copying the newly created .tmLanguage.json to .json-tmLanguage would be the best way forward if that file is being used in Sublime Text 2.

**Programming Languages**
I was inspecting the package.json file, just to learn and understand whilst looking at the [following documents](https://code.visualstudio.com/docs/extensionAPI/extension-manifest), which showed the correct value to be used.

Thanks for the info about version numbers ;)

Cheers

Mark

**Comment by fushnisoft** [comment]
>Casing: - package.json

As discussed on skype, these case changes turned out to be unnecessary so please undo them back to the original state. That way I think we are safer for compatibility with already released packages/extensions.

>Clarion.tmlanguage.json

The `Clarion.JSON-tmLanguage` is the starting point for the others though so we can't generate that from the `tmLanguage.json`.
The workflow is like this:
SublimeText 2 support - define syntax in `Clarion.JSON-tmLanguage`
  - Use the [PackageDev](https://github.com/SublimeText/PackageDev) package to generate `Clarion.tmLanguage`
SublimeText 3 - is backwards compatible with `Clarion.tmLanguage`
VSCode - referencing `Clarion.JSON-tmLanguage` in the `package.json` doesn't work but creating a copy of `Clarion.JSON-tmLanguage` called `Clarion.tmLanguage.json` and referencing that in `package.json` does!

The simplest and most broadly supported change here is to just do that copy and rename for VSCode.

**Pull request merged**
